<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;net48</TargetFrameworks>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <LangVersion>8.0</LangVersion>
    </PropertyGroup>

    <PropertyGroup>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <DebugType>embedded</DebugType>
    </PropertyGroup>

    <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>

    <PropertyGroup>
        <NoWarn>$(NoWarn);CS1591;CA2227</NoWarn>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <AnalysisLevel>latest</AnalysisLevel>
    </PropertyGroup>

    <!--
    # CS1591: Missing XML comment for publicly visible type or member.
    # CA2227: Collection properties should be read only.
    -->

    <PropertyGroup>
        <Authors>Peyman Mohammadi</Authors>
        <PackageIcon>icon.png</PackageIcon>
        <PackageId>MovieCollection.TVMaze</PackageId>
        <Copyright>© 2026 Peyman Mohammadi</Copyright>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageTags>movie; series; api; wrapper; tvmaze</PackageTags>
        <Description>Unofficial implementation of TVMaze API</Description>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <RepositoryUrl>https://github.com/moviecollection/tv-maze</RepositoryUrl>
        <PackageProjectUrl>https://github.com/moviecollection/tv-maze</PackageProjectUrl>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\README.md" Pack="true" PackagePath="\" />
        <None Include="..\..\Assets\icon.png" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
        <Reference Include="System.Net.Http" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="18.7.23">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

</Project>
